### ISSUE TITLE
MXNetError: GPU is not enabled

### ISSUE THREAD

**Issue by ExcaliburEX** [wangcn0201/Auto-STGCN#1]
我的CUDA是10.0的
装完
`mxnet_cu100==1.7.0`(主要`mxnet_cu100`没有`1.6.0.post0`版本)
`mxnet==1.7.0.post1`
运行，出现下列问题：

```bash
episode:1/10000
state:
[-2 -1 -1 -1 -1]
action:[1 1 1 2]    random
state:
[-1  1  1  1  2]
action:[2 2 1 2]    random
state:
[0 2 2 1 2]
action:[1 1 1 0]    QTable
state:
[1 1 1 1 0]
action:[-1 -1 -1 -1]    random
Traceback (most recent call last):
  File "Auto_STGCN.py", line 192, in <module>
    train_QTable(config, config_filename.replace('./Config/', '').replace("/", "_").split('.')[0])
  File "Auto_STGCN.py", line 101, in train_QTable
    next_obs, reward, done, info = env.step(action)
  File "/home/excalibur/pycharm_project/Auto-STGCN/Env.py", line 116, in step
    reward, flag = self.train_model(self.training_stage_action)
  File "/home/excalibur/pycharm_project/Auto-STGCN/Env.py", line 140, in train_model
    model.initialize(ctx=self.ctx)
  File "/home/excalibur/anaconda3/envs/torch/lib/python3.7/site-packages/mxnet/gluon/block.py", line 656, in initialize
    self.collect_params().initialize(init, ctx, verbose, force_reinit)
  File "/home/excalibur/anaconda3/envs/torch/lib/python3.7/site-packages/mxnet/gluon/parameter.py", line 893, in initialize
    v.initialize(None, ctx, init, force_reinit=force_reinit)
  File "/home/excalibur/anaconda3/envs/torch/lib/python3.7/site-packages/mxnet/gluon/parameter.py", line 469, in initialize
    self._finish_deferred_init()
  File "/home/excalibur/anaconda3/envs/torch/lib/python3.7/site-packages/mxnet/gluon/parameter.py", line 353, in _finish_deferred_init
    self._init_impl(data, ctx)
  File "/home/excalibur/anaconda3/envs/torch/lib/python3.7/site-packages/mxnet/gluon/parameter.py", line 365, in _init_impl
    self._data = [data.copyto(ctx) for ctx in self._ctx_list]
  File "/home/excalibur/anaconda3/envs/torch/lib/python3.7/site-packages/mxnet/gluon/parameter.py", line 365, in <listcomp>
    self._data = [data.copyto(ctx) for ctx in self._ctx_list]
  File "/home/excalibur/anaconda3/envs/torch/lib/python3.7/site-packages/mxnet/ndarray/ndarray.py", line 2666, in copyto
    return _internal._copyto(self, out=hret)
  File "<string>", line 27, in _copyto
  File "/home/excalibur/anaconda3/envs/torch/lib/python3.7/site-packages/mxnet/_ctypes/ndarray.py", line 91, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/home/excalibur/anaconda3/envs/torch/lib/python3.7/site-packages/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "src/ndarray/ndarray.cc", line 1298
MXNetError: GPU is not enabled

```

求赐教，感谢！:smile: 👍 😥 : # @wangcn0201

**Comment by GIS-PuppetMaster** [comment]
应该是安装不正确吧，参考这个https://discuss.mxnet.apache.org/t/mxneterror-gpu-not-enabled/446/4

**Comment by ExcaliburEX** [comment]
> 应该是安装不正确吧，参考这个https://discuss.mxnet.apache.org/t/mxneterror-gpu-not-enabled/446/4

- 感谢回复:smile:，把`CPU`版本卸载了，然后不用`Ubuntu`之前下载的`mxnet_cu100==1.7.0`的`cache`，转向清华镜像再重新下载安装就行了。

- 不过貌似我的2070 Super 8G版显存不够，`batch`调成[8 16 32]貌似也不成，这10000个eposide大概要跑多久啊:cry:

**Comment by GIS-PuppetMaster** [comment]
> > 应该是安装不正确吧，参考这个https://discuss.mxnet.apache.org/t/mxneterror-gpu-not-enabled/446/4
> 
> * 感谢回复😄，把`CPU`版本卸载了，然后不用`Ubuntu`之前下载的`mxnet_cu100==1.7.0`的`cache`，转向清华镜像再重新下载安装就行了。
> * 不过貌似我的2070 Super 8G版显存不够，`batch`调成[8 16 32]貌似也不成，这10000个eposide大概要跑多久啊😢

虽然设置的10000，但是实际训练的时候用wandb监控进度手动early stop的，一般2000episodes左右就可以了，2070肯定不行，V100（16G）都吃力

**Comment by GIS-PuppetMaster** [comment]
> > 应该是安装不正确吧，参考这个https://discuss.mxnet.apache.org/t/mxneterror-gpu-not-enabled/446/4
> 
> * 感谢回复😄，把`CPU`版本卸载了，然后不用`Ubuntu`之前下载的`mxnet_cu100==1.7.0`的`cache`，转向清华镜像再重新下载安装就行了。
> * 不过貌似我的2070 Super 8G版显存不够，`batch`调成[8 16 32]貌似也不成，这10000个eposide大概要跑多久啊😢

这版代码不是最终版的，有些bug，感兴趣的话可以等下一版更新，不过个人家用PC训练GCN应该是比较困难的，里面有几个组件很吃显存

**Comment by ExcaliburEX** [comment]
> > > 应该是安装不正确吧，参考这个https://discuss.mxnet.apache.org/t/mxneterror-gpu-not-enabled/446/4
> > 
> > 
> > 
> > * 感谢回复😄，把`CPU`版本卸载了，然后不用`Ubuntu`之前下载的`mxnet_cu100==1.7.0`的`cache`，转向清华镜像再重新下载安装就行了。
> > * 不过貌似我的2070 Super 8G版显存不够，`batch`调成[8 16 32]貌似也不成，这10000个eposide大概要跑多久啊😢
> 
> 虽然设置的10000，但是实际训练的时候用wandb监控进度手动early stop的，一般2000episodes左右就可以了，2070肯定不行，V100（16G）都吃力

懂啦，那只能看看学习学习啦~

**Comment by ExcaliburEX** [comment]
> > > 应该是安装不正确吧，参考这个https://discuss.mxnet.apache.org/t/mxneterror-gpu-not-enabled/446/4
> > 
> > 
> > 
> > * 感谢回复😄，把`CPU`版本卸载了，然后不用`Ubuntu`之前下载的`mxnet_cu100==1.7.0`的`cache`，转向清华镜像再重新下载安装就行了。
> > * 不过貌似我的2070 Super 8G版显存不够，`batch`调成[8 16 32]貌似也不成，这10000个eposide大概要跑多久啊😢
> 
> 这版代码不是最终版的，有些bug，感兴趣的话可以等下一版更新，不过个人家用PC训练GCN应该是比较困难的，里面有几个组件很吃显存

期待一下下一版~
